# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- Release/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) SharpBatch.sln /property:Version=1.0.0-CI$(Build.BuildId)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: 'test/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: PublishPipelineArtifact@0
  displayName: 'Artifact SharpBatch'
  inputs:
    artifactName: 'drop.SharpBatch'
    targetPath: 'src/SharpBatch/bin/Release'
- task: PublishPipelineArtifact@0
  displayName: 'Artifact SharpBatch.Abstraction'
  inputs:
    artifactName: 'drop.SharpBatch.Abstraction'
    targetPath: 'src/SharpBatch.Abstraction/bin/Release'